name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
    OUTPUT_PATH: ${{ github.workspace }}/.output
    DOTNET_VERSION: "3.1.16"
jobs:
  build:

    runs-on: Windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x    
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
